### ISSUE TITLE
Additional pin support

### ISSUE THREAD

**Issue by MrYsLab** [julianduque/beaglebone-io#9]
Would it be possible to specify additional pins outside of the hardcoded pin mapping. 
I am using the BeagleBone Bacon cape, and it has a button switch on P8_19, and I would like to access it, or any other pin without having to change the source code.

I am actively developing a project using Johnny-Five that includes support for the BBB: http://goo.gl/janKSR

Thanks.

**Comment by jlommori** [comment]
Hi

Did this issue ever get resolved? Can you help point me in the right direction to map other pins? I'm happy to modify the source if needed.

**Comment by troywweber7** [comment]
I'm also looking for a viable solution to this. J5 seems like the way to go. I decided to start working with the BeagleBone (I was using firmata over a usb to an Arduino before) because it has more pins to work with. Any information on how to add additional pins would be awesome. Also, it might be less confusion if pins were referred to by their `P#_##` instead of by Arduino pin numbers. Seems to obfuscate the concept of wiring up projects, but that's just my opinion.

**Comment by fivdi** [comment]
Apologies for taking so long to respond to this issue. PR #32 addresses the issue and if merged will provide support for many more pins.

**Comment by julianduque** [comment]
v2.0.0 has been published, thanks to great work by @fivdi
